services:
services:
  - type: worker
    name: crypto-signal-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: COINGLASS_API_KEY
        sync: false
